<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активность',
    'Create' => 'Создать',
    'Create page' => 'Создать страницу',
    'Create section' => 'Создать раздел',
    'Create subsection' => 'Создать подраздел',
    'Created at' => 'Дата создания',
    'Creator' => 'Создатель',
    'Display order' => 'Порядок отображения',
    'Name' => 'Название',
    'Page' => 'Страница',
    'Page successful created' => 'Страница успешно создана',
    'Page successful deleted' => 'Страница успешно удалена',
    'Page successful updated' => 'Страница успешно обновлена',
    'Pages' => 'Страницы',
    'Parent section' => 'Родительский раздел',
    'Root section' => 'Корневой раздел',
    'Section' => 'Раздел',
    'Section not found' => 'Раздел не найден',
    'Section successful created' => 'Раздел успешно создан',
    'Section successful deleted' => 'Раздел успешно удален',
    'Section successful updated' => 'Раздел успешно обновлен',
    'Update' => 'Редактировать',
    'Update page: {name}' => 'Редактирование страницы: {name}',
    'Update section: {name}' => 'Редактирование раздела: {name}',
    'Updated at' => 'Дата обновления',
    'Updater' => 'Обновивший',
    'You can not move a section to a child' => 'Вы не можете перенести этот раздел в дочерний',
    'You can not transfer the partition to itself' => 'Вы не можете перенести раздел сам в себя',
];
