<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Create' => '',
    'Create page' => '',
    'Create section' => '',
    'Create subsection' => '',
    'Created at' => '',
    'Creator' => '',
    'Display order' => '',
    'Name' => '',
    'Page' => '',
    'Page successful created' => '',
    'Page successful deleted' => '',
    'Page successful updated' => '',
    'Pages' => '',
    'Parent section' => '',
    'Root section' => '',
    'Section' => '',
    'Section not found' => '',
    'Section successful created' => '',
    'Section successful deleted' => '',
    'Section successful updated' => '',
    'Update' => '',
    'Update page: {name}' => '',
    'Update section: {name}' => '',
    'Updated at' => '',
    'Updater' => '',
    'You can not move a section to a child' => '',
    'You can not transfer the partition to itself' => '',
];
